### ISSUE TITLE
Fails to compile on MacOSX 10.10

### ISSUE THREAD

**Issue by maasha** [readmapping/essaMEM#1]
(Possibly a Clang vs GCC issue)

Error:

```
g++ -O3 -DNDEBUG -Wall -c mummer.cpp
mummer.cpp:93:10: error: reference to 'forward' is ambiguous
      if(forward){
         ^
mummer.cpp:28:6: note: candidate found by name lookup is 'forward'
bool forward = true;
     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1583:1: note: candidate found by name lookup is 'std::__1::forward'
forward(typename std::remove_reference<_Tp>::type& __t) _NOEXCEPT
^
mummer.cpp:93:10: error: unknown type name 'forward'
      if(forward){
         ^
mummer.cpp:93:17: error: expected unqualified-id
      if(forward){
                ^
mummer.cpp:93:17: error: variable declaration in condition must have an initializer
mummer.cpp:145:10: error: reference to 'forward' is ambiguous
      if(forward){
         ^
mummer.cpp:28:6: note: candidate found by name lookup is 'forward'
bool forward = true;
     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1583:1: note: candidate found by name lookup is 'std::__1::forward'
forward(typename std::remove_reference<_Tp>::type& __t) _NOEXCEPT
^
mummer.cpp:145:10: error: unknown type name 'forward'
      if(forward){
         ^
mummer.cpp:145:17: error: expected unqualified-id
      if(forward){
                ^
mummer.cpp:145:17: error: variable declaration in condition must have an initializer
mummer.cpp:312:7: error: reference to 'forward' is ambiguous
      forward = false;
      ^
mummer.cpp:28:6: note: candidate found by name lookup is 'forward'
bool forward = true;
     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1583:1: note: candidate found by name lookup is 'std::__1::forward'
forward(typename std::remove_reference<_Tp>::type& __t) _NOEXCEPT
^
9 errors generated.
make: *** [mummer.o] Error 1
```

Particulars:

```
Darwin edna 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

**Comment by symcong** [comment]
Execuse me ,Do you solve the problem?

**Comment by iehdk** [comment]
Nope. Sorry.
